/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SilentSwapV2Gateway {
  export type DepositParamsStruct = {
    signer: AddressLike;
    orderId: BytesLike;
    notary: AddressLike;
    approver: AddressLike;
    orderApproval: BytesLike;
    approvalExpiration: BigNumberish;
    duration: BigNumberish;
    domainSepHash: BytesLike;
    payloadHash: BytesLike;
    typedDataSignature: BytesLike;
    receiveAuthorization: BytesLike;
  };

  export type DepositParamsStructOutput = [
    signer: string,
    orderId: string,
    notary: string,
    approver: string,
    orderApproval: string,
    approvalExpiration: bigint,
    duration: bigint,
    domainSepHash: string,
    payloadHash: string,
    typedDataSignature: string,
    receiveAuthorization: string
  ] & {
    signer: string;
    orderId: string;
    notary: string;
    approver: string;
    orderApproval: string;
    approvalExpiration: bigint;
    duration: bigint;
    domainSepHash: string;
    payloadHash: string;
    typedDataSignature: string;
    receiveAuthorization: string;
  };
}

export interface SilentSwapDepositorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositProxy"
      | "depositProxy2"
      | "gatewayAddress"
      | "owner"
      | "renounceOwnership"
      | "sweep"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositProxy"
      | "DepositProxy2"
      | "OwnershipTransferred"
      | "Sweep"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositProxy",
    values: [SilentSwapV2Gateway.DepositParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositProxy2",
    values: [SilentSwapV2Gateway.DepositParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "gatewayAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sweep", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "depositProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositProxy2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gatewayAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace DepositProxyEvent {
  export type InputTuple = [
    signer: AddressLike,
    orderId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [signer: string, orderId: string, amount: bigint];
  export interface OutputObject {
    signer: string;
    orderId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositProxy2Event {
  export type InputTuple = [
    signer: AddressLike,
    orderId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [signer: string, orderId: string, amount: bigint];
  export interface OutputObject {
    signer: string;
    orderId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweepEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SilentSwapDepositor extends BaseContract {
  connect(runner?: ContractRunner | null): SilentSwapDepositor;
  waitForDeployment(): Promise<this>;

  interface: SilentSwapDepositorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositProxy: TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;

  depositProxy2: TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;

  gatewayAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sweep: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositProxy"
  ): TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositProxy2"
  ): TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gatewayAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sweep"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DepositProxy"
  ): TypedContractEvent<
    DepositProxyEvent.InputTuple,
    DepositProxyEvent.OutputTuple,
    DepositProxyEvent.OutputObject
  >;
  getEvent(
    key: "DepositProxy2"
  ): TypedContractEvent<
    DepositProxy2Event.InputTuple,
    DepositProxy2Event.OutputTuple,
    DepositProxy2Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Sweep"
  ): TypedContractEvent<
    SweepEvent.InputTuple,
    SweepEvent.OutputTuple,
    SweepEvent.OutputObject
  >;

  filters: {
    "DepositProxy(address,bytes32,uint256)": TypedContractEvent<
      DepositProxyEvent.InputTuple,
      DepositProxyEvent.OutputTuple,
      DepositProxyEvent.OutputObject
    >;
    DepositProxy: TypedContractEvent<
      DepositProxyEvent.InputTuple,
      DepositProxyEvent.OutputTuple,
      DepositProxyEvent.OutputObject
    >;

    "DepositProxy2(address,bytes32,uint256)": TypedContractEvent<
      DepositProxy2Event.InputTuple,
      DepositProxy2Event.OutputTuple,
      DepositProxy2Event.OutputObject
    >;
    DepositProxy2: TypedContractEvent<
      DepositProxy2Event.InputTuple,
      DepositProxy2Event.OutputTuple,
      DepositProxy2Event.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Sweep(address,uint256)": TypedContractEvent<
      SweepEvent.InputTuple,
      SweepEvent.OutputTuple,
      SweepEvent.OutputObject
    >;
    Sweep: TypedContractEvent<
      SweepEvent.InputTuple,
      SweepEvent.OutputTuple,
      SweepEvent.OutputObject
    >;
  };
}
