/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SilentSwapV2Gateway {
  export type ConfigStruct = {
    minDuration: BigNumberish;
    maxDuration: BigNumberish;
    minDepositAmount: BigNumberish;
  };

  export type ConfigStructOutput = [
    minDuration: bigint,
    maxDuration: bigint,
    minDepositAmount: bigint
  ] & { minDuration: bigint; maxDuration: bigint; minDepositAmount: bigint };

  export type ClaimSpecStruct = { orderId: BytesLike; signature: BytesLike };

  export type ClaimSpecStructOutput = [orderId: string, signature: string] & {
    orderId: string;
    signature: string;
  };

  export type BulkClaimParamsStruct = {
    claims: SilentSwapV2Gateway.ClaimSpecStruct[];
    recipient: AddressLike;
  };

  export type BulkClaimParamsStructOutput = [
    claims: SilentSwapV2Gateway.ClaimSpecStructOutput[],
    recipient: string
  ] & {
    claims: SilentSwapV2Gateway.ClaimSpecStructOutput[];
    recipient: string;
  };

  export type DepositParamsStruct = {
    signer: AddressLike;
    orderId: BytesLike;
    notary: AddressLike;
    approver: AddressLike;
    orderApproval: BytesLike;
    approvalExpiration: BigNumberish;
    duration: BigNumberish;
    domainSepHash: BytesLike;
    payloadHash: BytesLike;
    typedDataSignature: BytesLike;
    receiveAuthorization: BytesLike;
  };

  export type DepositParamsStructOutput = [
    signer: string,
    orderId: string,
    notary: string,
    approver: string,
    orderApproval: string,
    approvalExpiration: bigint,
    duration: bigint,
    domainSepHash: string,
    payloadHash: string,
    typedDataSignature: string,
    receiveAuthorization: string
  ] & {
    signer: string;
    orderId: string;
    notary: string;
    approver: string;
    orderApproval: string;
    approvalExpiration: bigint;
    duration: bigint;
    domainSepHash: string;
    payloadHash: string;
    typedDataSignature: string;
    receiveAuthorization: string;
  };
}

export interface SilentSwapV2GatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "addApprover"
      | "addClaimer"
      | "authorizedApprovers"
      | "authorizedClaimers"
      | "claim"
      | "claimsCap"
      | "config"
      | "deposit"
      | "depositProxy"
      | "getConfig"
      | "getSignerCount"
      | "isAuthorizedApprover"
      | "isAuthorizedClaimer"
      | "orders"
      | "owner"
      | "payloads"
      | "pendingOwner"
      | "queryOrderStatus"
      | "refund"
      | "removeApprover"
      | "removeClaimer"
      | "renounceOwnership"
      | "setClaimsCap"
      | "setConfig"
      | "signerCounts"
      | "transferOwnership"
      | "usdc"
      | "verifyTypedDataSignature"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApproverAdded"
      | "ApproverRemoved"
      | "Claim"
      | "ClaimerAdded"
      | "ClaimerRemoved"
      | "ConfigUpdated"
      | "Deposit"
      | "Error"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ProxyDeposit"
      | "Refund"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addApprover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addClaimer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedApprovers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedClaimers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [SilentSwapV2Gateway.BulkClaimParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "claimsCap", values?: undefined): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [SilentSwapV2Gateway.DepositParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositProxy",
    values: [SilentSwapV2Gateway.DepositParamsStruct, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSignerCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedApprover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedClaimer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payloads", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queryOrderStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeApprover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeClaimer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimsCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signerCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyTypedDataSignature",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addClaimer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedClaimers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimsCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSignerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedClaimer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payloads", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryOrderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeClaimer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimsCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signerCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyTypedDataSignature",
    data: BytesLike
  ): Result;
}

export namespace ApproverAddedEvent {
  export type InputTuple = [approver: AddressLike];
  export type OutputTuple = [approver: string];
  export interface OutputObject {
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApproverRemovedEvent {
  export type InputTuple = [approver: AddressLike];
  export type OutputTuple = [approver: string];
  export interface OutputObject {
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimEvent {
  export type InputTuple = [
    orderId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimerAddedEvent {
  export type InputTuple = [claimer: AddressLike];
  export type OutputTuple = [claimer: string];
  export interface OutputObject {
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimerRemovedEvent {
  export type InputTuple = [claimer: AddressLike];
  export type OutputTuple = [claimer: string];
  export interface OutputObject {
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    minDuration: BigNumberish,
    maxDuration: BigNumberish,
    minDepositAmount: BigNumberish
  ];
  export type OutputTuple = [
    minDuration: bigint,
    maxDuration: bigint,
    minDepositAmount: bigint
  ];
  export interface OutputObject {
    minDuration: bigint;
    maxDuration: bigint;
    minDepositAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    signer: AddressLike,
    orderId: BytesLike,
    amount: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    signer: string,
    orderId: string,
    amount: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    signer: string;
    orderId: string;
    amount: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ErrorEvent {
  export type InputTuple = [reason: string];
  export type OutputTuple = [reason: string];
  export interface OutputObject {
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyDepositEvent {
  export type InputTuple = [
    signer: AddressLike,
    orderId: BytesLike,
    amount: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    signer: string,
    orderId: string,
    amount: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    signer: string;
    orderId: string;
    amount: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundEvent {
  export type InputTuple = [
    orderId: BytesLike,
    refundee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [orderId: string, refundee: string, amount: bigint];
  export interface OutputObject {
    orderId: string;
    refundee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SilentSwapV2Gateway extends BaseContract {
  connect(runner?: ContractRunner | null): SilentSwapV2Gateway;
  waitForDeployment(): Promise<this>;

  interface: SilentSwapV2GatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addApprover: TypedContractMethod<
    [approver: AddressLike],
    [void],
    "nonpayable"
  >;

  addClaimer: TypedContractMethod<[claimer: AddressLike], [void], "nonpayable">;

  authorizedApprovers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizedClaimers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  claim: TypedContractMethod<
    [params: SilentSwapV2Gateway.BulkClaimParamsStruct],
    [bigint],
    "nonpayable"
  >;

  claimsCap: TypedContractMethod<[], [bigint], "view">;

  config: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        minDuration: bigint;
        maxDuration: bigint;
        minDepositAmount: bigint;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;

  depositProxy: TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getConfig: TypedContractMethod<
    [],
    [SilentSwapV2Gateway.ConfigStructOutput],
    "view"
  >;

  getSignerCount: TypedContractMethod<[signer: AddressLike], [bigint], "view">;

  isAuthorizedApprover: TypedContractMethod<
    [approver: AddressLike],
    [boolean],
    "view"
  >;

  isAuthorizedClaimer: TypedContractMethod<
    [claimer: AddressLike],
    [boolean],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, string, bigint] & {
        status: bigint;
        expiration: bigint;
        notary: string;
        refundee: string;
        amount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payloads: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  queryOrderStatus: TypedContractMethod<[orderId: BytesLike], [bigint], "view">;

  refund: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  removeApprover: TypedContractMethod<
    [approver: AddressLike],
    [void],
    "nonpayable"
  >;

  removeClaimer: TypedContractMethod<
    [claimer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setClaimsCap: TypedContractMethod<
    [newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<
    [
      minimumDuration: BigNumberish,
      maximumDuration: BigNumberish,
      minimumDepositAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  signerCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  verifyTypedDataSignature: TypedContractMethod<
    [
      domainSepHash: BytesLike,
      payloadHash: BytesLike,
      typedDataSignature: BytesLike,
      signer: AddressLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addApprover"
  ): TypedContractMethod<[approver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addClaimer"
  ): TypedContractMethod<[claimer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedApprovers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedClaimers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [params: SilentSwapV2Gateway.BulkClaimParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimsCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        minDuration: bigint;
        maxDuration: bigint;
        minDepositAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositProxy"
  ): TypedContractMethod<
    [params: SilentSwapV2Gateway.DepositParamsStruct, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<[], [SilentSwapV2Gateway.ConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "getSignerCount"
  ): TypedContractMethod<[signer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedApprover"
  ): TypedContractMethod<[approver: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedClaimer"
  ): TypedContractMethod<[claimer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, string, bigint] & {
        status: bigint;
        expiration: bigint;
        notary: string;
        refundee: string;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payloads"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queryOrderStatus"
  ): TypedContractMethod<[orderId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeApprover"
  ): TypedContractMethod<[approver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeClaimer"
  ): TypedContractMethod<[claimer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setClaimsCap"
  ): TypedContractMethod<[newCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [
      minimumDuration: BigNumberish,
      maximumDuration: BigNumberish,
      minimumDepositAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signerCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyTypedDataSignature"
  ): TypedContractMethod<
    [
      domainSepHash: BytesLike,
      payloadHash: BytesLike,
      typedDataSignature: BytesLike,
      signer: AddressLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ApproverAdded"
  ): TypedContractEvent<
    ApproverAddedEvent.InputTuple,
    ApproverAddedEvent.OutputTuple,
    ApproverAddedEvent.OutputObject
  >;
  getEvent(
    key: "ApproverRemoved"
  ): TypedContractEvent<
    ApproverRemovedEvent.InputTuple,
    ApproverRemovedEvent.OutputTuple,
    ApproverRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Claim"
  ): TypedContractEvent<
    ClaimEvent.InputTuple,
    ClaimEvent.OutputTuple,
    ClaimEvent.OutputObject
  >;
  getEvent(
    key: "ClaimerAdded"
  ): TypedContractEvent<
    ClaimerAddedEvent.InputTuple,
    ClaimerAddedEvent.OutputTuple,
    ClaimerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimerRemoved"
  ): TypedContractEvent<
    ClaimerRemovedEvent.InputTuple,
    ClaimerRemovedEvent.OutputTuple,
    ClaimerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Error"
  ): TypedContractEvent<
    ErrorEvent.InputTuple,
    ErrorEvent.OutputTuple,
    ErrorEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProxyDeposit"
  ): TypedContractEvent<
    ProxyDepositEvent.InputTuple,
    ProxyDepositEvent.OutputTuple,
    ProxyDepositEvent.OutputObject
  >;
  getEvent(
    key: "Refund"
  ): TypedContractEvent<
    RefundEvent.InputTuple,
    RefundEvent.OutputTuple,
    RefundEvent.OutputObject
  >;

  filters: {
    "ApproverAdded(address)": TypedContractEvent<
      ApproverAddedEvent.InputTuple,
      ApproverAddedEvent.OutputTuple,
      ApproverAddedEvent.OutputObject
    >;
    ApproverAdded: TypedContractEvent<
      ApproverAddedEvent.InputTuple,
      ApproverAddedEvent.OutputTuple,
      ApproverAddedEvent.OutputObject
    >;

    "ApproverRemoved(address)": TypedContractEvent<
      ApproverRemovedEvent.InputTuple,
      ApproverRemovedEvent.OutputTuple,
      ApproverRemovedEvent.OutputObject
    >;
    ApproverRemoved: TypedContractEvent<
      ApproverRemovedEvent.InputTuple,
      ApproverRemovedEvent.OutputTuple,
      ApproverRemovedEvent.OutputObject
    >;

    "Claim(bytes32,address,uint256)": TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;
    Claim: TypedContractEvent<
      ClaimEvent.InputTuple,
      ClaimEvent.OutputTuple,
      ClaimEvent.OutputObject
    >;

    "ClaimerAdded(address)": TypedContractEvent<
      ClaimerAddedEvent.InputTuple,
      ClaimerAddedEvent.OutputTuple,
      ClaimerAddedEvent.OutputObject
    >;
    ClaimerAdded: TypedContractEvent<
      ClaimerAddedEvent.InputTuple,
      ClaimerAddedEvent.OutputTuple,
      ClaimerAddedEvent.OutputObject
    >;

    "ClaimerRemoved(address)": TypedContractEvent<
      ClaimerRemovedEvent.InputTuple,
      ClaimerRemovedEvent.OutputTuple,
      ClaimerRemovedEvent.OutputObject
    >;
    ClaimerRemoved: TypedContractEvent<
      ClaimerRemovedEvent.InputTuple,
      ClaimerRemovedEvent.OutputTuple,
      ClaimerRemovedEvent.OutputObject
    >;

    "ConfigUpdated(uint256,uint256,uint256)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "Deposit(address,bytes32,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Error(string)": TypedContractEvent<
      ErrorEvent.InputTuple,
      ErrorEvent.OutputTuple,
      ErrorEvent.OutputObject
    >;
    Error: TypedContractEvent<
      ErrorEvent.InputTuple,
      ErrorEvent.OutputTuple,
      ErrorEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProxyDeposit(address,bytes32,uint256,uint256)": TypedContractEvent<
      ProxyDepositEvent.InputTuple,
      ProxyDepositEvent.OutputTuple,
      ProxyDepositEvent.OutputObject
    >;
    ProxyDeposit: TypedContractEvent<
      ProxyDepositEvent.InputTuple,
      ProxyDepositEvent.OutputTuple,
      ProxyDepositEvent.OutputObject
    >;

    "Refund(bytes32,address,uint256)": TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;
    Refund: TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;
  };
}
