/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IEIP3009Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizationState"
      | "cancelAuthorization"
      | "receiveWithAuthorization"
      | "transferWithAuthorization"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuthorizationCanceled" | "AuthorizationUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizationState",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuthorization",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveWithAuthorization",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferWithAuthorization",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizationState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferWithAuthorization",
    data: BytesLike
  ): Result;
}

export namespace AuthorizationCanceledEvent {
  export type InputTuple = [authorizer: AddressLike, nonce: BytesLike];
  export type OutputTuple = [authorizer: string, nonce: string];
  export interface OutputObject {
    authorizer: string;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizationUsedEvent {
  export type InputTuple = [authorizer: AddressLike, nonce: BytesLike];
  export type OutputTuple = [authorizer: string, nonce: string];
  export interface OutputObject {
    authorizer: string;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEIP3009 extends BaseContract {
  connect(runner?: ContractRunner | null): IEIP3009;
  waitForDeployment(): Promise<this>;

  interface: IEIP3009Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizationState: TypedContractMethod<
    [authorizer: AddressLike, nonce: BytesLike],
    [boolean],
    "view"
  >;

  cancelAuthorization: TypedContractMethod<
    [
      authorizer: AddressLike,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  receiveWithAuthorization: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferWithAuthorization: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizationState"
  ): TypedContractMethod<
    [authorizer: AddressLike, nonce: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAuthorization"
  ): TypedContractMethod<
    [
      authorizer: AddressLike,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveWithAuthorization"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferWithAuthorization"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      validAfter: BigNumberish,
      validBefore: BigNumberish,
      nonce: BytesLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizationCanceled"
  ): TypedContractEvent<
    AuthorizationCanceledEvent.InputTuple,
    AuthorizationCanceledEvent.OutputTuple,
    AuthorizationCanceledEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizationUsed"
  ): TypedContractEvent<
    AuthorizationUsedEvent.InputTuple,
    AuthorizationUsedEvent.OutputTuple,
    AuthorizationUsedEvent.OutputObject
  >;

  filters: {
    "AuthorizationCanceled(address,bytes32)": TypedContractEvent<
      AuthorizationCanceledEvent.InputTuple,
      AuthorizationCanceledEvent.OutputTuple,
      AuthorizationCanceledEvent.OutputObject
    >;
    AuthorizationCanceled: TypedContractEvent<
      AuthorizationCanceledEvent.InputTuple,
      AuthorizationCanceledEvent.OutputTuple,
      AuthorizationCanceledEvent.OutputObject
    >;

    "AuthorizationUsed(address,bytes32)": TypedContractEvent<
      AuthorizationUsedEvent.InputTuple,
      AuthorizationUsedEvent.OutputTuple,
      AuthorizationUsedEvent.OutputObject
    >;
    AuthorizationUsed: TypedContractEvent<
      AuthorizationUsedEvent.InputTuple,
      AuthorizationUsedEvent.OutputTuple,
      AuthorizationUsedEvent.OutputObject
    >;
  };
}
